### PR TITLE
Test/admin dashboard unit tests

### LINKED ISSUE #998: [Testing]: Write unit tests for admin dashboard components
## Description
The admin dashboard (#990) was recently merged. It needs unit tests for its components and API route.

## Tasks
- [ ] Test API route authentication and authorization
- [ ] Test user management endpoints
- [ ] Test system analytics data aggregation
- [ ] Test UI component rendering with mock data

## Labels
gssoc:approved, level:intermediate, type:testing, mentor:muneerali199

### PR DESCRIPTION
**Pull request by aaniya22**
# Description
Adds unit tests for the admin dashboard components and data flows introduced in #990, as requested in #998. Also fixes a bug in `lib/admin-auth.ts` discovered while writing the auth tests: it imported `createClient` from `@/lib/supabase/server`, but that file only exports `createServer`/`createRoute`/`createSupabaseAdmin`. This meant `requireAdmin()` — called in `app/admin/layout.tsx` on every admin page — crashed immediately with "createClient is not a function", breaking the entire admin dashboard at runtime.

Fixes #998

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] This change requires a documentation update

(Test additions don't fit the listed categories cleanly — this PR is primarily test coverage, plus one small bug fix needed to make the auth logic testable.)

## Changes Made
- Fixed broken `createClient` import in `lib/admin-auth.ts` (aliased to the correct `createServer` export)
- Added `lib/__tests__/admin-auth.test.ts` — tests `requireAdmin` and `isAdmin` (redirect on no user, redirect on non-admin role, redirect on missing profile, returns user when admin)
- Added `app/admin/__tests__/users-page.test.tsx` — tests user table rendering and the Supabase query (table, ordering, limit)
- Added `app/admin/__tests__/overview-page.test.tsx` — tests the user/document count aggregation and null-count fallback
- Added `app/admin/__tests__/config-page.test.tsx` — tests static config table rendering

## Dependencies
None added. (`npm install` was needed locally to pick up `@next/bundle-analyzer`, which was already in `package.json` but missing from `node_modules`.)

# How Has This Been Tested?
Ran the new suites directly and the full project test suite.
- [x] Test A — `npx jest lib/__tests__/admin-auth.test.ts app/admin/__tests__/` → 4 suites, 16 tests, all passing
- [x] Test B — `npx jest` (full suite) → 30 suites, 410 tests, all passing

## Add Screenshots
N/A — no UI changes, test-only PR (plus the one-line import fix).

## Checklist
- [x] My code follows the style guidelines of this project
- [ ] I have tested my changes across major browsers/devices
- [x] I have tested my changes in development mode (`npm run dev`)
- [ ] I have successfully run `npm run lint` and resolved all warnings/errors
- [ ] I have successfully run `npm run typecheck` and resolved all TypeScript errors
- [x] New and existing unit tests pass locally with my changes (`npx jest`)
- [x] I have written or updated related tests, if necessary
- [x] This is already assigned Issue to me, not an unassigned issue.
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

## Summary by CodeRabbit

* **Tests**
  * Added comprehensive test coverage for admin pages including configuration, overview, and user management sections.
  * Added test coverage for admin authentication and authorization helpers to ensure proper access control.

* **Chores**
  * Updated admin authentication module configuration for improved maintainability.

### CODE REVIEW

**Review by Muneerali199 — APPROVED** [review]
Solid test coverage for admin dashboard. Also fixes the createClient import bug discovered during testing. 16 tests pass. LGTM.
